### ISSUE TITLE
Sync should verify content hash if file already exists

### ISSUE THREAD

**Issue by erhhung** [shadiakiki1986/dbxcli-extras#1]
It doesn't appear that the current sync implementation checks whether a file that already exists in Dropbox is indeed the same local file, only that it exists, in which case it skips the put operation.

To ensure correct syncing, including possibly adding an option to delete remote files, the file content hash should be compared (see https://www.dropbox.com/developers/reference/content-hash).

**Comment by shadiakiki1986** [comment]
Done, released v0.0.5 and updated example notebook to demonstrate. Let me know if this works for you.

https://gist.github.com/shadiakiki1986/7c478d451a4221d464d7bcfd5fc6a914
