### ISSUE TITLE
Sync doesn't upload changes to existing files

### ISSUE THREAD

**Issue by TFesmire** [shadiakiki1986/dbxcli-extras#3]
I have a Team folder in Dropbox called `TestTeamFolder`. I used the `getr` subcommand to download the files to my volume. That worked fine. One of the files, `test.xlsx`, was modified using Excel and then saved. Running the `sync` subcommand did not upload the changes to the remote (Dropbox). However, adding a new file to the local folder, `test2.xlsx`, worked as expected after running the `sync` subcommand; `test2.xlsx` appeared in the remote folder listing.

Is `sync` supposed to compare the hash of local files with the remote hashes or is it more basic than that? It looks like it is only pushing new files to the remote. Similarly, deleting a file from the local folder did not propagate to the remote after running `sync`.

I appreciate the work that went into this tool, but the documentation does not explain how it works at all.

**Comment by shadiakiki1986** [comment]
You're right. I'll make some improvements and get back to you

**Comment by shadiakiki1986** [comment]
Done for the sync, released v0.0.5 and updated example notebook to demonstrate. Let me know if this works for you.

https://gist.github.com/shadiakiki1986/7c478d451a4221d464d7bcfd5fc6a914

For locally deleted file, unfortunately as you found, the feature isn't there. I'm kind of tight on time, but PRs welcome

**Comment by shadiakiki1986** [comment]
Added feature to check files deleted locally and delete them on dropbox. Released v0.0.6. Let me know if this works for your
